### PR TITLE
Revert "Initial command based robot boilerplate (#38)"

### PR DESCRIPTION
**Pull request by tcdoan**
This reverts commit 90f691562561a736af3cbf0948a89318a99cbf4b.

Address reviewer's comments on PR #38 and try to merge to main again.

### CODE REVIEW

**Comment by AadityaAgni** [comment]
Wait, so all this pr does is revert the commit right?

**Comment by tcdoan** [comment]
> Wait, so all this pr does is revert the commit right?
Yes. This is how we do things... standard procedure...

**Comment by AadityaAgni** [comment]
If no one else is here I could probably just accept it?

**Comment by tcdoan** [comment]
> Wait, so all this pr does is revert the commit right?

There are 2 ways to address a 'bad' merge. Teja could work on a new PR to rectify the issue or more commonly someone can revert his commit. The advantage of reverting commit is it is fast to turn around and can be done without waiting for the original commit author.

@AadityaAgni - Looks like Teja and Camila are not responding. I added you as reviewer. Can you approve the revert PR?

**Review by AadityaAgni — APPROVED** [review]
Looks good, since you are just reverting.

**Comment by AadityaAgni** [comment]
Just did, you should be able to merge now

**Review by ConfettiRaindrop — APPROVED** [review]

**Pull request merged**
